### ISSUE TITLE
Explain the concepts in glossary from a technical perspective

### ISSUE THREAD

**Issue by caro401** [DHARPA-Project/kiara-website#14]
This should eventually live somewhere separate, but for the moment, I'm mostly concerned with capturing the relevant information _somewhere_ to help share the understanding within the team. 

The current glossary file is [concepts/glossary.md](https://github.com/DHARPA-Project/kiara-website/blob/main/concepts/glossary.md) and contains some terminology which we all use. We should document what all these things are from a technical perspective, eg an operation is a python class which subclasses X and implements Y. Assume the target audience is very familiar with python, but not at all familiar with kiara. Short-ish definitions are good, especially for deeper concepts like the store and context - we can link out to much more detailed things when they exist (#12 etc)

see #8 for context, and for adding the higher level conceptual definitions.

**Comment by makkus** [comment]
So should I add this directly to the glossary, or somewhere else? Use MB like Caitlinn did CB?

**Comment by caro401** [comment]
I have no opinion, just want the information to exist somewhere
